//AUTH TYPES
export const AUTH_USER = 'AUTH_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE'
export const PASSWORD_RESET =  'PASSWORD_RESET'

//TASKS TYPES
export const LIST_CATEGORIES = 'LIST_CATEGORIES'
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'