//AUTH TYPES
export const AUTH_USER = 'AUTH_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE'
export const PASSWORD_RESET =  'PASSWORD_RESET'

//LIST
export const LIST_CATEGORIES = 'LIST_CATEGORIES'
export const LIST_PROJECTS = 'LIST_PROJECTS'
export const LIST_TASKS = 'LIST_TASKS'

//ADD
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_TASK = 'ADD_TASK'

//DELETE
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_TASK = 'DELETE_TASK'

//UPDATE


//CLEAR
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS'
export const CLEAR_TASKS = 'CLEAR_TASKS'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_STATUS = 'CLEAR_STATUS'